### ISSUE TITLE
On windows, Extract Local variable completely mess the Groovy editor content

### ISSUE THREAD

**Issue by apupier** [groovy/groovy-eclipse#157]
- On windows, try to refactor by extracting a local variable
  --> at first sight : the last character is missing and a line is duplicated. When yoy start clicking elsewhere, some lines are duplicated, others vanished

Initial state:
![image](https://cloud.githubusercontent.com/assets/1105127/11591480/5c15d030-9a98-11e5-8ec6-446392b03c72.png)
Extract Variable:
![errorrefatcor](https://cloud.githubusercontent.com/assets/1105127/11591577/1f2e26c6-9a99-11e5-9980-741eda611a2d.png)

Just after extract:
![image](https://cloud.githubusercontent.com/assets/1105127/11591523/b11f8b8e-9a98-11e5-9ee7-591947b314ba.png)
notice that the editor is nto set as dirty

start to just click elsewhere:
![image](https://cloud.githubusercontent.com/assets/1105127/11591540/cbd3df66-9a98-11e5-94c0-19d683366304.png)

or select several characters:
![image](https://cloud.githubusercontent.com/assets/1105127/11591548/d73a7554-9a98-11e5-9014-40594698c742.png)

If I close the editor and reopen it, the refatcor was done correctly

**Comment by eric-milles** [comment]
This happens to the editor when a CRLF is reduced to just CR or LF.  I have seen it with import additions.  This should be fixed now.

**Comment by monrealis** [comment]
With Eclipse Neon.3, it is not fixed as of 2017-06-30. I will check it with Oxygen.

**Comment by monrealis** [comment]
The problem remains in Eclipse Oxygen on Windows 10 with Groovy-Eclipse Feature 2.9.2.xx-201706301847-e47 too.

See the attached files:
[TestCaseAndVideo.zip](https://github.com/groovy/groovy-eclipse/files/1116536/TestCaseAndVideo.zip)

**Comment by eric-milles** [comment]
Must still be splitting the CRLF.  I will see if I can reproduce and fix.

**Comment by monrealis** [comment]
Thanks!

P.S. Test case is attached. I will test the fix as soon as I update groovy-eclipse.

**Comment by monrealis** [comment]
Thanks, the problem is fixed in Groovy-Eclipse Feature 2.9.2.xx-201707192351-e47.
